### ISSUE TITLE
Remove hard dependency on Rails/ActiveRecord?

### ISSUE THREAD

**Issue by m-o-e** [hlascelles/que-scheduler#1]
I'm using Que with Sequel and would love to add que-scheduler.

Unfortunately the latter currently has a hard dependency to AR baked in.
Are there any plans to change that? :)

**Comment by hlascelles** [comment]
Your wish is my command. I've created a branch with a working implementation. Would you be able to test it from there for me? https://github.com/hlascelles/que-scheduler/pull/2

If it works out for you I'll cut a gem.

**Comment by m-o-e** [comment]
Sweet!  I've left a comment on the PR.

**Comment by hlascelles** [comment]
Moving this conversation to the PR... https://github.com/hlascelles/que-scheduler/pull/2
