### ISSUE TITLE
SQL error while running migration

### ISSUE THREAD

**Issue by sapraaman** [hlascelles/que-scheduler#13]
I am following the steps mentioned in the readme file. However, while running db:migrate, I am seeing this error:

```
StandardError: An error has occurred, this and all later migrations canceled:

ERROR:  column "args" is of type jsonb but expression is of type json
LINE 16: SELECT scheduler_job_id, (enqueued->>'args')::json AS args, ...
                                   ^
HINT:  You will need to rewrite or cast the expression.
```

Any idea what could be causing this ?

**Comment by hlascelles** [comment]
It appears there was a change in the way json columns are cast. I'm guessing you're on postgres 9.4.

I've made the cast more exact, so now it will run on postgres 9.4 instances. I'll cut a new gem today.
