### ISSUE TITLE
Does this work with que 1.0.0.beta?

### ISSUE THREAD

**Issue by fameoflight** [hlascelles/que-scheduler#14]
Just wondering if you had a chance to look if there are any breaking api changes?

**Comment by hlascelles** [comment]
Good question! There are some great changes coming in que it seems.

I had a quick look through que-scheduler today, and it seems *almost* entirely compatible. I've [created a PR](https://github.com/hlascelles/que-scheduler/pull/18) to track que's master branch.

Given what I've found so far, it won't be difficult to make the next version of que-scheduler compatible with both 0.10.x and 1.0.x.

**Comment by hlascelles** [comment]
I'll close this for now and keep track on the related PR.
