### ISSUE TITLE
Automatically create que-scheduler job if it is missing/has-been-accidentally-deleted

### ISSUE THREAD

**Issue by i2chris** [hlascelles/que-scheduler#209]
I'm concerned about the consequences would be if somebody accidentally deleted the que-scheduler job that is required to schedule all other jobs.   I accidentally did this when I first setup que-scheduler before I realised how it works.

I'm concerned that someone might accidentally do this in future.  The consequences would be catastrophic for me.

What's the best mechanism to ensure that that the job is always running?

I'm thinking that I could do a check occasionally in the web process and create the new job.  

Is there a function I can call which will create this job if it is missing?

Thanks

**Comment by hlascelles** [comment]
I know what you mean. I don't have a simple answer to this, as `que-scheduler` leverages the stability and HA of a distributed task processing system - `que` itself. There is no way for "itself" to know that it has been deleted, there is no other "process" involved.

I would say something like "no-one should be deleting jobs from your DB if they don't know what they are doing", but I understand mistakes can happen.

I think it probably dovetails with this issue: https://github.com/hlascelles/que-scheduler/issues/161

Once we have a diagnostics command, then it can be added as a healthcheck. Assuming your app also has a healthcheck endpoint like [okcomputer](https://github.com/sportngin/okcomputer) then it could be configured to start erroring if the scheduler job is missing / failing. Actually on second thoughts that would make the health check think the service is unhealthy and kill it if you are using autoscaling. Maybe the healthcheck could "autoheal" and enqueue a new scheduler job (though that too could be considered a side-effect of a GET).

Slightly more aggressive ideas could be: whenever an event triggered job happens it could always first check the scheduler. But that might be overkill / use more resources.

Does any of the above sound useful?

In any regard, the command to run in a console to "get it back" is `Que::Scheduler::SchedulerJob.enqueue`, but that will enqueue 2 if one already exists - but don't worry, it has "duplicate scheduler" [checking in place](https://github.com/hlascelles/que-scheduler/blob/master/lib/que/scheduler/state_checks.rb#L64) so it won't start double scheduling.

**Comment by hlascelles** [comment]
Actually, a much simpler solution - we could add a trigger on the table so that when a row is deleted, and if it has `job_class` "Que::Scheduler::SchedulerJob", then do a select to check there is another one scheduled. 

If there isn't, then it is being deleted in error, and the trigger can raise an exception.

**Comment by AlanLattimore** [comment]
It's a common pattern over the lifespan of long projects to squash migrations by capturing the schema and deleting all migrations up to the capture point.

If that capture point is after `Que::Scheduler::Migrations.migrate!`, `migrate_up` won't run.

**Comment by hlascelles** [comment]
Good point about squashing migrations. I think que-scheduler falls somewhere between DDL and DML, so it will be an interesting one to handle.

I am opening a PR now which will go some way to solving all of this. https://github.com/hlascelles/que-scheduler/pull/224 

It will ensure at the DB level, using triggers,  that once the scheduler is started it can't be accidentally deleted. Also it will ensure that not more than one scheduler can be enqueued at once. This has all been enforced before using ruby, but the DB is even more exacting.

I will keep this issue open to look at the ways to make the job be "auto-added" if (eg) migrations have been squashed and a new environment is being created.

**Comment by AlanLattimore** [comment]
Thank you for a wonderful gem!

If only there was a pre-startup callback available from within Que.locker that would allow que_scheduler to check for `Que::Scheduler::SchedulerJob`

**Comment by hlascelles** [comment]
You are very kind :blush:.

Thank you for all the feedback. I have pushed version [4.0.0](https://rubygems.org/gems/que-scheduler/versions/4.0.0). It is a major version change as it comes with a requirement of a migration up to "migrations version 6":

`Que::Scheduler::Migrations.migrate!(version: 6)`

This will add a sparse unique index and a trigger to ensure the scheduler job is never lost. You can see the main change in the PR here: https://github.com/hlascelles/que-scheduler/pull/224/files#diff-26fbd2f9313514a37742f7d2d07c4a8c6f81ef21f6bd02856183416dcc11417cR2

This will (I believe) solve the problem for "new installations" and "current installations migrating". People will have to do some very specific trigger disabling to delete the job now, so I am going to rule out any future "accidental" deletions. I debated "que-scheduler reinserting the job itself whenever Rails started up" but given the 90% case is solved, I don't want to add unexpected INSERT statements, or extra table queries (if the check was more frequent). It's a tough one to decide though.

That just left squashed migrations. (NB, que doesn't work with the `schema.rb` format: https://github.com/que-rb/que#additional-rails-specific-setup. It must be `schema.sql` to support squashing correctly). I have done a change with another PR which will cover this with documentation and a utility method. https://github.com/hlascelles/que-scheduler/pull/226
This resulted in gem [4.0.2](https://rubygems.org/gems/que-scheduler/versions/4.0.2).

I am going to close this as covering all of the above as best I can. Let me know if there is more you think I can try!

**Comment by i2chris** [comment]
Thanks for your work on this! Merry Christmas!
