### ISSUE TITLE
Version compatibility/Migration path

### ISSUE THREAD

**Issue by etal2** [hlascelles/que-scheduler#24]
Updating from 1.2.0 to 2.1.2 broke my project, I see 3.0 is out now.
How do I migrate from an older version? Just run migrations again?
Are the new features documented somewhere?

**Comment by hlascelles** [comment]
Hi etal... Good questions, I will update the README to reflect all that follows. PR opened: https://github.com/hlascelles/que-scheduler/pull/25

In short, expect major versions to come with breaking changes, and a one liner cumulative migration will bring your DB up to speed. 

I've also added an issue to make the gem error cleanly and report what migration it requires if necessary. https://github.com/hlascelles/que-scheduler/issues/26

## DB Migrations

When there is a major version (breaking) change, a migration should be run in. The version of the 
migration proceeds at a faster rate than the version of the gem. To run in all the migrations required
up to a number, just migrate to that number. 

ie, `Que::Scheduler::Migrations.migrate!(version: 4)` will perform all migrations necessary to 
reach migration version `4`.

As of migration `4`, two elements are added to the DB for que-scheduler to run. 

1. The first is the scheduler job itself, which runs forever, re-enqueuing itself to performs its 
   duties.
1. The second part comprises the audit table `que_scheduler_audit` and the "enqueued" table 
  `que_scheduler_audit`. The first tracks when the scheduler calculated what was necessary to run 
  (if anything). The second then logs every job that the scheduler enqueues. 

## Upgrading

que-scheduler uses [semantic versioning](https://semver.org/), so major version changes will usually 
require additional actions to be taken upgrading from one major version to another. 

The full [CHANGELOG](https://github.com/hlascelles/que-scheduler/blob/master/CHANGELOG.md) can be
found in the root of the project. 

#### Versions 3.x 
  - Addition of numerous extra columns to the audit table.
  - Requires migration: `Que::Scheduler::Migrations.migrate!(version: 5)`
#### Versions 2.x 
  - Introduction of the audit table.
  - Support for older versions of postgres
  - Requires migration: `Que::Scheduler::Migrations.migrate!(version: 4)`
#### Versions 1.x
  - Sequel support
  - Config specified Timezone support
  - Requires migration: `Que::Scheduler::Migrations.migrate!(version: 2)`
#### Versions 0.x
  - The first public release. 
  - Requires migration: `Que::Scheduler::Migrations.migrate!(version: 1)`

**Comment by hlascelles** [comment]
As a side note, I anticipate the gem release rate to now stabilise, though I am always happy to take PRs!

**Comment by etal2** [comment]
Thanks, Is it safe to migrate directly from version 1.x to 3.x or do I have to go through 2.x first?

**Comment by hlascelles** [comment]
You can go straight to 3.x with one migration: `Que::Scheduler::Migrations.migrate!(version: 4)`. That will do a cumulative migration all the way.
