### ISSUE TITLE
Dynamically add/remove jobs

### ISSUE THREAD

**Issue by a0s** [hlascelles/que-scheduler#258]
Hi! I am wondering if there is an option to add/remove new jobs "on the fly"? Something like

```ruby
class User < ApplicationRecord
  after_commit do
    self.job_id = Que::Scheduler.add_job('0 0 * * *', class: 'UserChecker', args: {user_id: self.id})
    self.save!
  end
  
  after_destroy do
    Que::Scheduler.remove_job(self.job_id)
  end
end
```

Need some example (or i missed it in the doc?) if this ability is present..

**Comment by hlascelles** [comment]
Interesting question. I do understand the use case, but I would do it a little differently.

You could use `que-scheduler` to just check everything daily like this. The job is triggered with no args and it figures out what to do, enqueueing many of itself with an id.

```ruby
class UserCheckerQueJob < Que::Job
  def run(id)
    ActiveRecord::Base.transaction do
      if id
        check_user(id)
      else
        User.pluck(:id).each do |id|
          UserCheckerQueJob.enqueue(id)
        end
      end
      destroy
    end
  end
end
```

```yaml
# que-schedule.yml
UserCheckerQueJob:
  cron: "0 0 * * *"
```

Would that work? It would be quite bursty, but que is very fast.
