### ISSUE TITLE
cannot CREATE INDEX "que_jobs" because it has pending trigger events

### ISSUE THREAD

**Issue by bjeanes** [hlascelles/que-scheduler#292]
When trying to upgrade Que:

```
ERROR:  cannot CREATE INDEX "que_jobs" because it has pending trigger events
/app/vendor/bundle/ruby/2.6.0/bundler/gems/que-61e1805deb81/lib/que/connection.rb:63:in `exec'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/que-61e1805deb81/lib/que/connection.rb:63:in `block in execute'
(eval):9:in `run_sql_middleware'
```

Has anybody seen this before?

**Comment by hlascelles** [comment]
Interesting, no not seen that before. The only thing I can find that may be related is this [issue](https://code.djangoproject.com/ticket/31106) in another project.

Can you describe the state the app is in (with versions) to cause this? And definitely a stack trace, I'd like to rescue this error and reraise with a better message if we can find out what it is. 

If you [disable_ddl_transaction! ](https://apidock.com/rails/ActiveRecord/Migration/disable_ddl_transaction!/class) you does the migration then pass?

**Comment by bjeanes** [comment]
Ah I forgot to update. We simply migrated que-scheduler down to v5 (which removes the trigger), then migrated Que, then migrated scheduler back up to v6.

**Comment by hlascelles** [comment]
Good stuff.
