### ISSUE TITLE
Undefined error when active job is included in other gem dependencies

### ISSUE THREAD

**Issue by ippachi** [hlascelles/que-scheduler#309]
First, thanks great gem 😄 

I use this plugin without ActiveJob but that is included in ActiveSupport dependencies.
So `Que::Scheduler::ToEnqueue.active_job_loaded?` returns true, but ActiveJob is undefined because I don't require and I don't want to use ActiveJob.

## My proposal
rename `active_job_loaded?` to `active_job_defined?` like below and replace to this.

```ruby
def active_job_defined?
  Object.const_defined?('ActiveJob')
end
```

This change may break compatibility.

If you think this change is good, I'll create PR.

**Comment by hlascelles** [comment]
Thank you for the report! Sorry for the delay...

OK, I think I understand the issue. I will have a look very shortly and may come back with some questions. And may take you up on the offer of a PR :).

**Comment by hlascelles** [comment]
OK, yes, I see what you mean. It *may* mean the users in the future have to `require "active_job"` before this gem. If it crops up we can add some defensive messaging.

I think let's go with this change, yes please to a PR!

**Comment by ippachi** [comment]
Thank you!
I'll try it this weekend 😄

**Comment by hlascelles** [comment]
Released! https://rubygems.org/gems/que-scheduler/versions/4.2.2
