### ISSUE TITLE
 Error: undefined method `name' for {"cron"=>"0 1 * * *"}:Hash #332 

### ISSUE THREAD

**Issue by toddkummer** [hlascelles/que-scheduler#314]
The schedule is not being parsed into an object, resulting in an error when it is read.

```
undefined method `name' for {"cron"=>"0 1 * * *"}:Hash

lib/ruby/gems/2.5.0/gems/que-scheduler-4.2.1/lib/que/scheduler/enqueueing_calculator.rb:19:in `block in parse'
lib/ruby/gems/2.5.0/gems/que-scheduler-4.2.1/lib/que/scheduler/enqueueing_calculator.rb:18:in `map'
lib/ruby/gems/2.5.0/gems/que-scheduler-4.2.1/lib/que/scheduler/enqueueing_calculator.rb:18:in `parse'
lib/ruby/gems/2.5.0/gems/que-scheduler-4.2.1/lib/que/scheduler/scheduler_job.rb:28:in `block in run'
lib/ruby/gems/2.5.0/gems/que-scheduler-4.2.1/lib/que/scheduler/db.rb:23:in `block in transaction'

```

The following monkey patch seems to resolve the issue:

```ruby
module Que
  module Scheduler
    class Schedule
      class << self
        def from_hash(config_hash)
          config_hash.map do |name, defined_job_hash|
            name_str = name.to_s
            [name_str, hash_item_to_defined_job(name_str, defined_job_hash)]
          end.to_h
        end
      end
    end
  end
end
```

The `map` was removed (replaced with `to_h`) in this commit:
https://github.com/hlascelles/que-scheduler/commit/6d2f950f263eaf13591d50518a3377b99a7ccdcd#diff-816c18226c519ce6a91c9f9fd70f20b7e2a5d891345369cf0dc3c99279744f23L39-R39

**Comment by hlascelles** [comment]
Thank you for this bug report! OK, yes, I can see that change working.

To replicate this exactly, can I see the code that is causing the issue? I'll add a test with it and fix it from there.

**Comment by toddkummer** [comment]
It happened during the SchedulerJob. The job sends the schedule to the EnqueueingCalculator:

`result = EnqueueingCalculator.parse(Scheduler.schedule.values, scheduler_job_args)`

The EnqueueingCalculator expects the schedule values to be an array of DefinedJob instances, but it is a hash. Thus the error noted.

The goal of the `from_hash` method appears to be a list of DefinedJob instances indexed by name. If that's the case, a more explicit way to do that might be as follows:

```
def from_hash(config_hash)
  config_hash
    .map { |name, defined_job_hash|  hash_item_to_defined_job(name.to_s, defined_job_hash) }
    .index_by(&:name)
  end
end
```

**Comment by hlascelles** [comment]
I'm having trouble producing a failing test for this.

Looking at this further, I see that the code as it stands, and the monkey patch, are the same from ruby 2.6 onwards.
Ruby 2.6 added `to_h` taking a block: https://rubyreferences.github.io/rubychanges/2.6.html#to_h-with-a-block

Is it possible you are using ruby 2.5? Support for that has been removed: https://github.com/hlascelles/que-scheduler/pull/281 as it is EOL. If so I could set a minimum version in the gemspec (and certainly put it in the README).

If you could show a failing test that would be very helpful.

Either way, I can make that last change that generates a hash by using `index_by` if it works for a wider range of users? I'll readd 2.5 on a "best effort" basis to the test matrix and see what happens.

**Comment by hlascelles** [comment]
Will tackle this with readding best effort ruby 2.5 support: https://github.com/hlascelles/que-scheduler/pull/318

**Comment by hlascelles** [comment]
Will add it, though "unsupported": https://github.com/hlascelles/que-scheduler/pull/320

**Comment by hlascelles** [comment]
Released! https://rubygems.org/gems/que-scheduler/versions/4.2.2

**Comment by toddkummer** [comment]
We did encounter the error on ruby 2.5. Apologies for not including that initially. Thanks for addressing the issue.
