### ISSUE TITLE
How to use with ruby3 branch?

### ISSUE THREAD

**Issue by fameoflight** [hlascelles/que-scheduler#329]
# Description

I am trying to use this with ruby3 branch, just getting started with new project. Any ideas how to unblock to launch the project will be appreciated.  

# Versions

master

# Messages

== 20220313185311 AddQueSchedulerSchema: migrating ============================
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

ERROR:  column "kwargs" of relation "que_jobs" does not exist
LINE 1: ...e_jobs (queue, priority, run_at, job_class, args, kwargs, da...
                                                             ^
/Users/hemantv/workspace/openzar/openzar-api/db/migrate/20220313185311_add_que_scheduler_schema.rb:3:in `change'

Caused by:
PG::UndefinedColumn: ERROR:  column "kwargs" of relation "que_jobs" does not exist
LINE 1: ...e_jobs (queue, priority, run_at, job_class, args, kwargs, da...
                                                             ^
/Users/hemantv/workspace/openzar/openzar-api/db/migrate/20220313185311_add_que_scheduler_schema.rb:3:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by hlascelles** [comment]
Hi @fameoflight. It looks like ruby 3 will require some refactoring of this gem to work. 

As I understand it, you can use one of two main setups:

que 0.x or que 1.x, with ruby 2.7

OR

que 2.x with ruby 3.0. That is still being worked on here: https://github.com/que-rb/que/pull/319

There is already work going on to support it (https://github.com/hlascelles/que-scheduler/pull/328), but I have largely been waiting for it to be released before I put serious effort into it, as the que changes may not yet be stable.

I will push a change to the README to highlight this :+1: .
