### ISSUE TITLE
Scheduling with ActiveJob

### ISSUE THREAD

**Issue by sega** [hlascelles/que-scheduler#42]
I am trying to use que-scheduler with Rails and ActiveJob. When I specify a subclass of ActiveJob::Base in my schedule, [this subclass check](https://github.com/hlascelles/que-scheduler/blob/master/lib/que/scheduler/defined_job.rb#L19) fails. Any hint what to do?

**Comment by hlascelles** [comment]
Ah yes, I can see what you mean. I don't use ActiveJob, but que-scheduler should support it. I will investigate.

**Comment by sega** [comment]
Maybe it would be sufficient to check for a `perform` instance method?

**Comment by hlascelles** [comment]
Yes, that looks like it would be a good fit. Could you produce a PR for it that works for that use case? I would be happy to merge it and cut a new gem.

**Comment by hlascelles** [comment]
Closed by https://github.com/hlascelles/que-scheduler/pull/164

Released: https://rubygems.org/gems/que-scheduler/versions/3.3.0
