### ISSUE TITLE
`Time.zone` can be `nil` in non-Rails applications

### ISSUE THREAD

**Issue by jordoh** [hlascelles/que-scheduler#98]
Rails has an initializer that sets ActiveRecord's `Time.zone_default`, but if you're not using Rails and don't specify a default zone, `Time.zone` will return `nil`, resulting in the following exception running the `SchedulerJob`:

```
NoMethodError: undefined method `parse' for nil:NilClass
  from que/scheduler/scheduler_job_args.rb:24:in `build'
  from que/scheduler/scheduler_job.rb:22:in `block in run'
  from que/scheduler/db.rb:22:in `block in transaction'
  from que/utils/transactions.rb:18:in `block in transaction'
  from que/connection_pool.rb:39:in `block in checkout'
  from que/active_record/connection.rb:13:in `block (2 levels) in checkout'
  from active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
  from que/active_record/connection.rb:12:in `block in checkout'
  from que/active_record/connection.rb:25:in `wrap_in_rails_executor'
  from que/active_record/connection.rb:11:in `checkout'
  from que/connection_pool.rb:18:in `checkout'
  from que/utils/transactions.rb:12:in `transaction'
  from que/scheduler/db.rb:22:in `call'
  from que/scheduler/db.rb:22:in `transaction'
  from que/scheduler/scheduler_job.rb:19:in `run'
  from que/job_methods.rb:47:in `_run'
  from que/worker.rb:96:in `tap'
  from que/worker.rb:96:in `block in work_job'
  from (eval):11:in `block in run_job_middleware'
  from que/utils/middleware.rb:41:in `invoke_middleware'
  from que/utils/middleware.rb:37:in `block in invoke_middleware'
  from que/active_record/connection.rb:33:in `call'
  from que/utils/middleware.rb:36:in `invoke_middleware'
  from (eval):11:in `run_job_middleware'
  from que/worker.rb:96:in `work_job'
  from que/worker.rb:69:in `work_loop'
  from que/worker.rb:46:in `block in initialize'
```

Would it be reasonable to fall back to `Time.current` (or simply use `Time.current`, which uses `Time.zone` if the zone is set and falls back to `Time.now` if it it isn't)? Or is this something that could/should be noted in the documentation?

**Comment by hlascelles** [comment]
Interesting, thank you for raising this. I will investigate the ramifications of both of those solutions and add some tests. I'm sure one of them will work!

**Comment by jordoh** [comment]
Thanks, for the moment I'm just setting the default in each worker thread with: 
```
Que.job_middleware.push(
  ->(_job, &block) {
    Time.zone = "UTC"
    block.call
  }
)
```
(`Time.zone = "UTC"` sets a thread-local)

**Comment by hlascelles** [comment]
I spent some time looking at this this weekend. It will be a change across the codebase with potentially subtle consequences, so I won't rush it. I might produce a branch which I could ask you to try too?

**Comment by jordoh** [comment]
> I spent some time looking at this this weekend. It will be a change across the codebase with potentially subtle consequences, so I won't rush it. I might produce a branch which I could ask you to try too?

Thanks, happy to try out a patch. Note that I'm running off of the `que-1.0-compatibility` branch, but it's no problem to fork and apply a patch to if that's an easier workflow for you.

**Comment by hlascelles** [comment]
OK... I am on a push to get the `que-1.0-compatibility` onto master (allowing the one published 1.x beta que version). That should make your life simpler, then I'll have a look at this?

**Comment by jordoh** [comment]
Sounds great, thanks. 👍

**Comment by hlascelles** [comment]
Hi @jordoh ...

A recent change went out that addressed a non-Rails scenario. https://github.com/hlascelles/que-scheduler/pull/213

Did that solve this problem for you?

**Comment by jordoh** [comment]
Hi @hlascelles - after updating to 4.0.2 and removing the [workaround I was using](https://github.com/hlascelles/que-scheduler/issues/98#issuecomment-512579624), I'm still seeing the same exception:
![image](https://user-images.githubusercontent.com/450345/100645342-6486e000-32f1-11eb-921d-6c48e06449ec.png)

**Comment by hlascelles** [comment]
Thank you for the feedback! I decided to add a full app integration test which will cover exactly this.

I have subsequently released [4.0.3](https://rubygems.org/gems/que-scheduler/versions/4.0.3) which includes the PR that will cater for this case: https://github.com/hlascelles/que-scheduler/pull/229.

It seems that if Rails is involved, we can rely on that config, but if it isn't, then we just must "ask". To use outside of Rails you can now use the new `time_zone` config item:

```ruby
Que::Scheduler.configure do |config|
  config.time_zone = "Europe/London"
end
```

Apologies this has taken so long, I hope it works out for you.

**Comment by jordoh** [comment]
@hlascelles - thanks for the update; `4.0.3` with the described initializer does the trick. 👍

**Comment by hlascelles** [comment]
Fantastic, thank you for your patience! :bow:
